### ISSUE TITLE
VMA - new vendor with ssh key

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#915] opened 2024-03-25 13:50 UTC
Metadata is going to being setting up VMA fetch interfaces for all OCLC worldshare collections. This will be a large number of new active vendors/interfaces and each will use the same OCLC credentials below. Pattern for vendor with ssh key exists for vendor [Amaliv](https://folio.stanford.edu/organizations/view/ae734c25-beb0-5794-9df5-75608483cb58) found [here](https://sul-libsys-airflow-prod.stanford.edu/vendor_management/vendors/2221). This is needed on stage and production.

Worldshare info 

FTP server 	sftp:filex-m1.oclc.org
FTP user 	fx_stf
FTP password 	/home/sirsi/.ssh/fx_stf
FTP remote directory 	/xfer/metacoll/out/ongoing/deletes*/xfer/metacoll/out/ongoing/new*/xfer/metacoll/out/ongoing/updates

**Comment by ahafele** [comment] 2024-04-18 16:07
Sample org/interface https://folio-stage.stanford.edu/organizations/view/1a399a97-9149-5fa0-9160-aee4e14a6699

**Comment by ahafele** [comment] 2024-04-22 18:31
@jermnelson this is failing for me https://sul-libsys-airflow-stage.stanford.edu/log?dag_id=data_fetcher&task_id=ftp_download_task&execution_date=2024-04-22T18:08:54%2B00:00

Interface is here - https://sul-libsys-airflow-stage.stanford.edu/vendor_management/interfaces/171

Files for loading are found inside zip file so I've configured the interface similar to marcit (our other zip file example) but error is saying no such file. Waiting to see if Jeanette can get me WMS credentials so I can log in to see what she does.

**Comment by jermnelson** [comment] 2024-04-22 19:05
@ahafele, I was able to log into the server and after looking around on the server, I think the problem is because the remote path should be absolute and start with a forward slash like `/xfer/metacoll/out/ongoing/new`. I clicked on the `Process Now` and the DAG run was successful: https://sul-libsys-airflow-stage.stanford.edu/dags/data_fetcher/grid?root=&dag_run_id=manual__2024-04-22T19%3A02%3A16%2B00%3A00 if you want to check and confirm.

**Comment by ahafele** [comment] 2024-04-22 22:11
This looks good now. Thanks! I will make a new ticket if we end up with a requirement to extract from zip files.

**Comment by jermnelson** [comment] 2024-04-22 23:04
@ahafele, I'm closing this ticket now but if we need to do more, please let me know and we can re-open.

**Closed by jermnelson** 2024-04-22 23:04 UTC
